# Generated by Django 5.0.7 on 2024-08-07 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('account_number', models.PositiveIntegerField(unique=True)),
                ('type', models.CharField(choices=[('s', 'Saving'), ('c', 'Current')], default='s', max_length=20)),
                ('initial_balance', models.FloatField(blank=True, null=True)),
                ('balance', models.FloatField(default=0.0)),
                ('account_holder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('transaction_id', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('c', 'Credit'), ('d', 'Debit')], max_length=20)),
                ('amount', models.FloatField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('t_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='account.account')),
            ],
            bases=('base.basemodel',),
        ),
    ]
