# Generated by Django 4.1.13 on 2024-08-11 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_failed_attempts_user_is_blocked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_blocked',
            new_name='is_locked',
        ),
    ]
