# Generated by Django 4.1.13 on 2024-08-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_is_blocked_user_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
